### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by bramus** [bramus/js-pagination-sequence#2]
![image](https://user-images.githubusercontent.com/213073/144765976-e49c66c3-72f3-437f-a843-bca26f12bc34.png "I don't always test my code. But when I do, I do it in production.")

**Comment by AleksandrHovhannisyan** [comment]
@bramus Are you accepting contributions for this issue? I'd be happy to write tests/add a test runner like jest.

**Comment by bramus** [comment]
@AleksandrHovhannisyan I'm open to PRs, especially for one that adds tests :)
